/*
    The benchmark results:
    criterion = "0.5.1"

    Hardware: Apple M4 Pro
    Total Number of Cores:	10
    (Inside multipass vm running Ubuntu 22.04)

    // Benchmark compares enabled vs disabled user events listener in the same group
    | Test                        | Average time|
    |-----------------------------|-------------|
    | user_events_logs/disabled   | 19.2 ns     |
    | user_events_logs/enabled    | 530 ns      |

    The benchmark automatically enables/disables the listener using tracefs
    (preferred) or debugfs (fallback) paths:
    //  echo 1 | sudo tee /sys/kernel/tracing/events/user_events/myprovider_L2K1/enable
    //  echo 0 | sudo tee /sys/kernel/tracing/events/user_events/myprovider_L2K1/enable

    Requirements:
    - Linux kernel 6.4+ with user_events support
    - Root privileges or CAP_SYS_ADMIN capability
    - tracefs mounted at /sys/kernel/tracing (preferred) or debugfs at /sys/kernel/debug/tracing
*/

// Running the benchmark:
// sudo -E ~/.cargo/bin/cargo bench --bench logs --all-features
//
// The benchmark will automatically skip if user_events are not supported
// on the current system (kernel < 6.4 or missing user_events support).

use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion};
use opentelemetry_appender_tracing::layer as tracing_layer;
use opentelemetry_sdk::logs::SdkLoggerProvider;
use opentelemetry_sdk::Resource;
use opentelemetry_user_events_logs::Processor;
use std::fs;
use std::io;
use tracing::error;
use tracing_subscriber::prelude::*;
use tracing_subscriber::Registry;

const PROVIDER_NAME: &str = "myprovider";
/// Suffix used by the kernel user_events provider naming in these benchmarks.
/// Documented to avoid magic strings in path construction.
///
/// The kernel appends a unique suffix (such as "_L2K1") to user events provider names
/// when registering them via the user_events interface. This suffix is generated by the
/// kernel to ensure uniqueness and to encode internal information about the provider.
/// In this benchmark, "_L2K1" is the suffix assigned by the kernel to the "myprovider"
/// provider. This value may differ across systems or kernel versions, and is required
/// when constructing sysfs paths for enabling/disabling the provider's listener, e.g.:
///   /sys/kernel/tracing/events/user_events/myprovider_L2K1/enable
/// For more details, see the Linux kernel documentation on user_events:
///   https://docs.kernel.org/trace/user_events.html
const USER_EVENTS_PROVIDER_SUFFIX: &str = "_L2K1";
/// Provider name used for dummy guards that perform no operations.
/// This value is not used for actual provider operations, only for internal tracking.
const DUMMY_PROVIDER_NAME: &str = "dummy";

/// RAII guard for enabling/disabling user events listener
///
/// This guard automatically enables the user events listener when created and
/// disables it when dropped, ensuring proper cleanup even if the benchmark
/// panics or exits early.
///
/// The guard tracks whether the listener was already enabled before it was
/// created, and only disables it on drop if it wasn't already enabled.
/// This prevents interfering with other tests or processes that might have
/// enabled the listener.
///
/// # Fields
/// * `provider_name` - The name of the kernel user events provider being managed by this guard.
///   This is used to construct sysfs paths and identify which provider's listener should be enabled or disabled.
///   It is essential for ensuring that the guard operates on the correct provider, especially when multiple
///   providers may exist or when running benchmarks that interact with different user events sources.
/// * `was_enabled` - Tracks whether the listener was already enabled before this guard was created.
///   This field is crucial for preventing the guard from disabling listeners that were enabled
///   by external processes or other parts of the system. When the guard is dropped, it only
///   disables the listener if `was_enabled` is false, ensuring that external processes that
///   may have enabled the listener for their own purposes are not disrupted.
/// * `is_dummy` - Indicates whether this is a dummy guard that performs no operations.
///   Dummy guards are created when enabling the listener fails, ensuring benchmarks can proceed
///   without attempting to disable anything later. When `is_dummy` is true, the drop implementation
///   performs no cleanup operations.
struct UserEventsListenerGuard {
    provider_name: String,
    was_enabled: bool,
    is_dummy: bool,
}

impl UserEventsListenerGuard {
    /// Check if user events are supported on this system
    ///
    /// This method checks if the user_events subsystem is available by
    /// reading from `/sys/kernel/tracing/user_events_status` (tracefs) or
    /// `/sys/kernel/debug/tracing/user_events_status` (debugfs) as fallback.
    ///
    /// # Returns
    /// * `true` - If user events are supported
    /// * `false` - If user events are not supported
    fn is_supported() -> bool {
        // Try tracefs first (preferred path)
        if fs::read_to_string("/sys/kernel/tracing/user_events_status").is_ok() {
            return true;
        }
        // Fallback to debugfs
        fs::read_to_string("/sys/kernel/debug/tracing/user_events_status").is_ok()
    }

    /// Get the base path for user events (tracefs preferred, debugfs fallback)
    ///
    /// # Returns
    /// * `Ok(String)` - The base path if user events are available
    /// * `Err(String)` - Error message if user events are not available
    fn get_base_path() -> Result<String, String> {
        // Try tracefs first (preferred path)
        if fs::read_to_string("/sys/kernel/tracing/user_events_status").is_ok() {
            return Ok("/sys/kernel/tracing".to_string());
        }
        // Fallback to debugfs
        if fs::read_to_string("/sys/kernel/debug/tracing/user_events_status").is_ok() {
            return Ok("/sys/kernel/debug/tracing".to_string());
        }
        Err("User events subsystem not available on this system".to_string())
    }

    /// Enable the user events listener for the given provider
    ///
    /// This method:
    /// 1. Checks if the listener is already enabled
    /// 2. Enables it if it's not already enabled
    /// 3. Returns a guard that will disable the listener on drop (if it wasn't already enabled)
    ///
    /// # Arguments
    /// * `provider_name` - The name of the provider to enable/disable
    ///
    /// # Returns
    /// * `Ok(Self)` - A guard that will disable the listener on drop
    /// * `Err(String)` - Error message if enabling failed
    fn enable(provider_name: &str) -> Result<Self, String> {
        let base_path = Self::get_base_path()?;
        let enable_path = format!(
            "{}/events/user_events/{}{}/enable",
            base_path, provider_name, USER_EVENTS_PROVIDER_SUFFIX
        );

        // Check if already enabled by reading the entire file and checking if it equals "1"
        let was_enabled = match fs::read_to_string(&enable_path) {
            Ok(contents) => contents.trim() == "1",
            Err(e) => {
                if e.kind() == io::ErrorKind::PermissionDenied {
                    return Err(format!(
                        "Insufficient permissions to read '{}'. Please run the benchmark as root or with appropriate capabilities (CAP_SYS_ADMIN). Error: {}",
                        enable_path, e
                    ));
                } else {
                    return Err(format!("Failed to check listener status: {}", e));
                }
            }
        };

        // Only enable the listener if it's not already enabled
        if !was_enabled {
            // Enable the listener by writing "1\n" to the enable file
            // Most sysfs/debugfs interfaces expect a newline character.
            if let Err(e) = fs::write(&enable_path, b"1\n") {
                if e.kind() == io::ErrorKind::PermissionDenied {
                    return Err(format!(
                        "Insufficient permissions to write to '{}'. Please run the benchmark as root or with appropriate capabilities (CAP_SYS_ADMIN). Error: {}",
                        enable_path, e
                    ));
                } else {
                    return Err(format!("Failed to enable listener: {}", e));
                }
            }
        }

        if was_enabled {
            println!(
                "User events listener was already enabled for provider: {}",
                provider_name
            );
        } else {
            println!(
                "User events listener enabled for provider: {}",
                provider_name
            );
        }

        Ok(UserEventsListenerGuard {
            provider_name: provider_name.to_string(),
            was_enabled,
            is_dummy: false,
        })
    }

    /// Check if user events are available on the system
    ///
    /// This method checks if the user_events subsystem is available by
    /// reading from tracefs or debugfs.
    ///
    /// # Returns
    /// * `Ok(String)` - The status content if user events are available
    /// * `Err(String)` - Error message if user events are not available
    fn check_user_events_available() -> Result<String, String> {
        let base_path = Self::get_base_path()?;
        let status_path = format!("{}/user_events_status", base_path);

        match fs::read_to_string(&status_path) {
            Ok(status) => Ok(status),
            Err(e) => {
                if e.kind() == io::ErrorKind::PermissionDenied {
                    Err(format!(
                        "Insufficient permissions to read '{}'. Please run the benchmark as root or with appropriate capabilities (CAP_SYS_ADMIN). Error: {}",
                        status_path, e
                    ))
                } else if e.kind() == io::ErrorKind::NotFound {
                    Err("User events subsystem not available on this system".to_string())
                } else {
                    Err(format!("Failed to check user events availability: {}", e))
                }
            }
        }
    }

    /// Create a dummy guard that performs no action on drop
    ///
    /// This is used when enabling the listener fails; it ensures the
    /// benchmark can proceed without attempting to disable anything later.
    fn dummy_guard() -> Self {
        UserEventsListenerGuard {
            provider_name: DUMMY_PROVIDER_NAME.to_string(),
            was_enabled: false, // Not relevant for dummy guards
            is_dummy: true,
        }
    }
}

impl Drop for UserEventsListenerGuard {
    fn drop(&mut self) {
        let base_path = match Self::get_base_path() {
            Ok(path) => path,
            Err(_) => return, // If we can't get the path, we can't disable anyway
        };
        let disable_path = format!(
            "{}/events/user_events/{}{}/enable",
            base_path, self.provider_name, USER_EVENTS_PROVIDER_SUFFIX
        );

        // Skip cleanup for dummy guards
        if self.is_dummy {
            return;
        }

        // Only disable if it wasn't already enabled
        if !self.was_enabled {
            match fs::write(&disable_path, b"0\n") {
                Ok(_) => {
                    eprintln!(
                        "User events listener disabled for provider: {}",
                        self.provider_name
                    );
                }
                Err(e) => {
                    if e.kind() == io::ErrorKind::PermissionDenied {
                        eprintln!(
                            "Failed to disable listener due to insufficient permissions. Please run the benchmark as root or with appropriate capabilities (CAP_SYS_ADMIN). Error: {}",
                            e
                        );
                    } else {
                        eprintln!("Failed to disable listener: {}", e);
                    }
                }
            }
        } else {
            eprintln!(
                "User events listener was already enabled, leaving enabled for provider: {}",
                self.provider_name
            );
        }
    }
}

fn setup_provider_default() -> SdkLoggerProvider {
    let user_event_processor = Processor::builder(PROVIDER_NAME).build().unwrap();

    SdkLoggerProvider::builder()
        .with_resource(
            Resource::builder_empty()
                .with_service_name("benchmark")
                .build(),
        )
        .with_log_processor(user_event_processor)
        .build()
}

fn bench_logs(c: &mut Criterion) {
    // Check if user events are supported, skip if not
    if !UserEventsListenerGuard::is_supported() {
        eprintln!("User events not supported on this system, skipping benchmarks");
        return;
    }

    let mut group = c.benchmark_group("user_events_logs");

    // 1) disabled
    group.bench_function(BenchmarkId::new("disabled", ""), |b| {
        let provider = setup_provider_default(); // создаёт user_events exporter/tracepoints
        let ot_layer = tracing_layer::OpenTelemetryTracingBridge::new(&provider);
        let subscriber = Registry::default().with(ot_layer);

        tracing::subscriber::with_default(subscriber, || {
            b.iter(|| {
                error!(
                    name : "CheckoutFailed",
                    field1 = "field1",
                    field2 = "field2",
                    field3 = "field3",
                    field4 = "field4",
                    message = "Unable to process checkout."
                );
            });
        });
        drop(provider);
    });

    // 2) enabled
    group.bench_function(BenchmarkId::new("enabled", ""), |b| {
        let provider = setup_provider_default();
        let _guard = UserEventsListenerGuard::enable(PROVIDER_NAME).expect("enable listener");
        let ot_layer = tracing_layer::OpenTelemetryTracingBridge::new(&provider);
        let subscriber = Registry::default().with(ot_layer);

        tracing::subscriber::with_default(subscriber, || {
            b.iter(|| {
                error!(
                    name : "CheckoutFailed",
                    field1 = "field1",
                    field2 = "field2",
                    field3 = "field3",
                    field4 = "field4",
                    message = "Unable to process checkout."
                );
            });
        });
        // guard в Drop отключит listener, если включал его он
        drop(_guard);
        drop(provider);
    });

    group.finish();
}

criterion_group!(benches, bench_logs);
criterion_main!(benches);
